spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;MODE=MYSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
websiteUrl: https://mystore.com