spring:
  jwt:
    secret: dummy-secret
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;MODE=MYSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
stripe:
  secretKey: dummy-secret
  webhookSecretKey: dummy-secret
websiteUrl: https://mystore.com